# Generated by Django 5.0.2 on 2024-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_remove_review_movie_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
