# Generated by Django 5.0.2 on 2024-03-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_review_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filmapp.movie'),
            preserve_default=False,
        ),
    ]
