# Generated by Django 5.0.2 on 2024-03-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
